export { getNextTag, peekNextTag } from './tag-counter'
export { loginWithEmail, loginWithGoogle, logout, onAuthChange, createUserByAdmin } from './auth-service'
export { addUser, getUsers, updateUser, deleteUser, getUserById, updateUserRole, toggleUserActive } from './users-service'
export { addSoftware, getSoftware, updateSoftware, deleteSoftware } from './software-service'
export { addBrand, getBrands, updateBrand, deleteBrand, getBrandById, migrateBrand } from './brands-service'
export { addDevice, getDevices, deleteDevice, getDevicesById, updateDevice, migrateDevice } from './device-service'
export { addComputer, getComputers, updateComputer, deleteComputer, getComputerById, reassignComputer } from './computer-service'
export { addCertificate, getCertificateNumber, getCertificates, getCertificateById, migrateCertificate, getLastCertificateNumber, deleteCertificate, updateCertificate } from './certificate-service'
export { addPrestamo, getPrestamos, deletePrestamo, updatePrestamoStatus } from './prestamos-service'
export { getAvailability, getAllAvailability, setAvailability } from './equipment-availability-service'