export { getNextTag } from './tag-counter'
export { loginWithEmail, loginWithGoogle, logout, onAuthChange } from './auth-service'
export { addUser, getUsers, updateUser, deleteUser, getUserById } from './users-service'
export { addSoftware, getSoftware, updateSoftware, deleteSoftware } from './software-service'
export { addBrand, getBrands, updateBrand, deleteBrand, getBrandById, migrateBrand } from './brands-service'
export { addDevice, getDevices, deleteDevice, getDevicesById, updateDevice, migrateDevice } from './device-service'
export { addComputer, getComputers, updateComputer, deleteComputer, getComputerById, reassignComputer } from './computer-service'
export { addCertificate, getCertificateNumber, getCertificates, getCertificateById, migrateCertificate, getLastCertificateNumber, deleteCertificate, updateCertificate } from './certificate-service'